# Development Configuration Example
# Local development setup with mock services

admin_base_path: "/admin"

lua_routing:
  enabled: true
  scripts_dir: "./scripts"

tenants:
  # Local API development
  - name: "dev-api"
    domains: ["localhost", "127.0.0.1", "dev.local"]
    lua_routes: "development-routes.lua"
    health_interval: 60  # Longer intervals for development
    services:
      - name: "local-backend"
        url: "http://localhost:3001"
        health: "/health"

  # Test path-based routing
  - name: "test-app"
    path_prefix: "/test/"
    lua_routes: "test-routes.lua"
    health_interval: 30
    services:
      - name: "test-service"
        url: "http://localhost:4000"
        health: "/status"

  # Mock external service
  - name: "mock-service"
    path_prefix: "/mock/"
    lua_routes: "mock-routes.lua"
    health_interval: 120
    services:
      - name: "mock-backend"
        url: "http://localhost:8000"
        health: "/ping"