# CHI-STONE: Clean Architecture Configuration
# This demonstrates the proper separation of concerns:
# - CHI-STONE (this file): Pure routing, health checks, load balancing
# - LUA-STONE (separate service): Lua script execution engine

# Admin endpoints configuration
admin_base_path: "/admin"

# Optional: lua-stone service integration
lua_engine:
  enabled: true
  url: "http://localhost:8081"  # lua-stone service
  timeout: "5s"

tenants:
  # Simple tenant without Lua scripting
  - name: "simple-app"
    domains: ["simple.example.com"]
    services:
      - name: "backend"
        url: "http://localhost:3000"
        health: "/health"

  # Advanced tenant with lua-stone scripting
  - name: "canary-api"
    domains: ["api.example.com"]
    lua_script: "canary"  # Script managed by lua-stone service
    services:
      - name: "api-stable"
        url: "http://localhost:3000"
        health: "/health"
      - name: "api-canary"
        url: "http://localhost:3001"
        health: "/health"

  # Path-based routing example
  - name: "api-service"
    path_prefix: "/api/"
    lua_script: "rate-limiting"  # Advanced features via lua-stone
    services:
      - name: "api-backend-1"
        url: "http://localhost:3002"
        health: "/health"
      - name: "api-backend-2"
        url: "http://localhost:3003"
        health: "/health"