# Multi-Tenant Configuration Example
# Demonstrates different routing strategies

admin_base_path: "/admin"

lua_routing:
  enabled: true
  scripts_dir: "./scripts/lua"

tenants:
  # Host-based routing tenant
  - name: "api-tenant"
    domains: ["api.example.com", "api.mysite.com"]
    lua_routes: "auth-routes.lua"
    health_interval: 30
    services:
      - name: "api-backend-1"
        url: "http://api-backend:3001"
        health: "/health"
      - name: "api-backend-2"
        url: "http://api-backend:3002"
        health: "/health"

  # Path-based routing tenant
  - name: "app-tenant"
    path_prefix: "/app/"
    lua_routes: "app-routes.lua"
    health_interval: 45
    services:
      - name: "app-backend"
        url: "http://app-service:4000"
        health: "/status"

  # Another host-based tenant
  - name: "legacy-tenant"
    domains: ["legacy.example.com"]
    lua_routes: "legacy-routes.lua"
    health_interval: 60
    services:
      - name: "legacy-service"
        url: "http://legacy-backend:8080"
        health: "/health-check"