# Production Configuration Example
# Production-ready setup with multiple environments

admin_base_path: "/admin"

lua_routing:
  enabled: true
  scripts_dir: "/opt/keystone/scripts"

tenants:
  # Production API
  - name: "prod-api"
    domains: ["api.production.com", "api.company.com"]
    lua_routes: "production-auth-routes.lua"
    health_interval: 15  # More frequent health checks in production
    services:
      - name: "api-prod-1"
        url: "http://api-prod-1.internal:3001"
        health: "/health"
      - name: "api-prod-2"
        url: "http://api-prod-2.internal:3001"
        health: "/health"
      - name: "api-prod-3"
        url: "http://api-prod-3.internal:3001"
        health: "/health"

  # Staging environment
  - name: "staging-api"
    domains: ["api.staging.com"]
    lua_routes: "staging-routes.lua"
    health_interval: 30
    services:
      - name: "api-staging"
        url: "http://api-staging.internal:3001"
        health: "/health"

  # Admin dashboard
  - name: "admin-dashboard"
    path_prefix: "/dashboard/"
    lua_routes: "admin-dashboard-routes.lua"
    health_interval: 60
    services:
      - name: "dashboard-backend"
        url: "http://dashboard.internal:8080"
        health: "/status"

  # Microservice routing
  - name: "microservices"
    path_prefix: "/services/"
    lua_routes: "microservice-routes.lua"
    health_interval: 20
    services:
      - name: "user-service"
        url: "http://user-service.internal:3000"
        health: "/health"
      - name: "order-service"
        url: "http://order-service.internal:3000"
        health: "/health"
      - name: "payment-service"
        url: "http://payment-service.internal:3000"
        health: "/health"
