# Simple Configuration Example
# Basic single-tenant setup for development

admin_base_path: "/admin"

# HTTP Response Compression Configuration
compression:
  enabled: true        # Enable/disable compression (default: true)
  level: 5            # Compression level 1-9 (default: 5, balanced)
  content_types:      # MIME types to compress (defaults shown)
    - "text/html"
    - "text/css"
    - "text/javascript"
    - "application/json"
    - "application/xml"
    - "text/plain"

lua_routing:
  enabled: true
  scripts_dir: "./scripts"
  # global_scripts: ["global-security"]

tenants:
  - name: "api"
    domains: ["127.0.0.1"]
    lua_routes: "basic-routes"
    health_interval: 30
    services:
      - name: "backend"
        url: "http://127.0.0.1:3001"
        health: "/health"