# Simple Configuration Example
# Basic single-tenant setup for development

admin_base_path: "/admin"

lua_routing:
  enabled: true
  scripts_dir: "./scripts"
  # global_scripts: ["global-security"]

tenants:
  - name: "api"
    domains: ["127.0.0.1"]
    lua_routes: "basic-routes"
    health_interval: 30
    services:
      - name: "backend"
        url: "http://127.0.0.1:3001"
        health: "/health"