tenants:
  - name: "api-service"
    path_prefix: "/api/"
    services:
      - name: "api-backend-1"
        url: "http://localhost:3000"
        health: "/health"
      - name: "api-backend-2"
        url: "http://localhost:3001"
        health: "/health"

  - name: "app-service"
    domains: ["app.example.com", "www.app.example.com"]
    services:
      - name: "app-backend-1"
        url: "http://localhost:3002"
        health: "/health"
      - name: "app-backend-2"
        url: "http://localhost:3003"
        health: "/health"

  - name: "mobile-api"
    domains: ["mobile.example.com"]
    path_prefix: "/mobile/"
    services:
      - name: "mobile-backend"
        url: "http://localhost:3004"
        health: "/health"