# Keystone Gateway Configuration with Embedded Lua Support
lua_routing:
  enabled: true
  scripts_dir: "./scripts/examples"
  timeout: "5s"

tenants:
  # Standard tenant without Lua scripting
  - name: "simple-app"
    domains: ["simple.example.com"]
    services:
      - name: "backend"
        url: "http://localhost:3000"
        health: "/health"

  # Canary deployment with Lua script
  - name: "canary-api"
    domains: ["api.example.com"]
    lua_routes: "canary-routes"  # references scripts/examples/canary-routes.lua
    services:
      - name: "api-stable"
        url: "http://backend-stable:80"
        health: "/"
        labels:
          version: "stable"
      - name: "api-canary"
        url: "http://backend-canary:80"
        health: "/"
        labels:
          version: "canary"

  # Blue/Green deployment
  - name: "bluegreen-app"
    domains: ["app.example.com"]
    lua_routes: "blue-green"
    services:
      - name: "app-blue"
        url: "http://localhost:3002"
        health: "/health"
        labels:
          environment: "blue"
      - name: "app-green"
        url: "http://localhost:3003"
        health: "/health"
        labels:
          environment: "green"

  # A/B Testing
  - name: "ab-test-service"
    domains: ["test.example.com"]
    lua_routes: "ab-testing"
    services:
      - name: "service-version-a"
        url: "http://localhost:3004"
        health: "/health"
        labels:
          version: "a"
      - name: "service-version-b"
        url: "http://localhost:3005"
        health: "/health"
        labels:
          version: "b"
