# Default configuration values for Keystone Gateway
# These values are used when not explicitly specified in environment configs

# Default admin API configuration  
admin_base_path: "/admin"

# Default Lua routing configuration
lua_routing:
  enabled: true
  scripts_dir: "./scripts"

# Default TLS configuration (disabled by default)
tls:
  enabled: false
  # cert_file: "/path/to/cert.pem"
  # key_file: "/path/to/key.pem" 

# Default compression configuration
compression:
  enabled: true
  level: 5  # Balanced compression level (1-9)
  content_types:
    - "text/html"
    - "text/css"
    - "text/javascript"
    - "application/json"
    - "application/xml"
    - "text/plain"

# Default health check interval (seconds)
default_health_interval: 30