extends:
  - '@commitlint/config-conventional'

rules:
  # Type enum with project-specific types
  type-enum:
    - 2
    - always
    - [
        'feat',      # New feature
        'fix',       # Bug fix
        'docs',      # Documentation only changes
        'style',     # Changes that do not affect meaning (formatting, etc)
        'refactor',  # Code change that neither fixes a bug nor adds a feature
        'perf',      # Performance improvement
        'test',      # Adding missing tests or correcting existing tests
        'chore',     # Changes to build process or auxiliary tools
        'ci',        # Continuous integration changes
        'build',     # Changes that affect build system or dependencies
        'revert'     # Reverts a previous commit
      ]

  # Scope enum with project-specific scopes
  scope-enum:
    - 2
    - always
    - [
        'routing',   # Gateway routing logic
        'config',    # Configuration management
        'health',    # Health checking system
        'proxy',     # Reverse proxy functionality
        'lua',       # Lua script integration
        'admin',     # Admin API endpoints
        'tests',     # Test infrastructure
        'ci',        # CI/CD pipeline
        'docker',    # Docker and containerization
        'deps',      # Dependencies
        'security',  # Security improvements
        'perf',      # Performance optimizations
        'docs'       # Documentation
      ]

  # Subject rules
  subject-case:
    - 2
    - never
    - ['sentence-case', 'start-case', 'pascal-case', 'upper-case']
  subject-empty:
    - 2
    - never
  subject-full-stop:
    - 2
    - never
    - '.'
  subject-max-length:
    - 2
    - always
    - 50

  # Header rules
  header-max-length:
    - 2
    - always
    - 72

  # Body rules
  body-leading-blank:
    - 1
    - always
  body-max-line-length:
    - 2
    - always
    - 72

  # Footer rules
  footer-leading-blank:
    - 1
    - always