admin_base_path: "/admin"

# Production-optimized settings
compression:
  enabled: true
  level: 6
  content_types:
    - "application/json"
    - "text/html"
    - "text/css"
    - "text/javascript"
    - "application/xml"

lua_routing:
  enabled: true
  scripts_dir: "./scripts/lua"

tenants:
  # Production API tenant
  - name: "production-api"
    domains:
      - "localhost"
      - "127.0.0.1"
      # Add your production domains here:
      # - "api.yourdomain.com"
      # - "gateway.yourdomain.com"
    lua_routes: "api-routes.lua"
    health_interval: 30
    services:
      # Replace with your actual backend services
      - name: "backend-service-1"
        url: "http://your-backend-1:8080"
        health: "/health"
      - name: "backend-service-2"
        url: "http://your-backend-2:8080"
        health: "/health"

  # Additional tenants can be added here
  # - name: "another-service"
  #   path_prefix: "/api/v2/"
  #   services:
  #     - name: "v2-backend"
  #       url: "http://v2-service:8080"
  #       health: "/health"
