# Simplified Production Configuration for Keystone Gateway
# Environment: Production (simplified)
# Last Updated: 2025-07-19

# Server Configuration
server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  max_header_bytes: 1048576

# Admin Configuration
admin:
  enabled: true
  base_path: "/admin"
  auth:
    enabled: true
    username: "admin"
    password: "opfeorpfer2"

# Routing Configuration
routing:
  # Host-based routing rules
  hosts:
    # Demo Application
    "demo.keystone-gateway.dev":
      upstream: "http://demo-backend:80"
      health_check: "/health"
      load_balancer: "round_robin"
      timeout: 30s
      retry_attempts: 3
      retry_delay: 1s

    # API Service
    "api.keystone-gateway.dev":
      upstream: "http://api-backend:3000"
      health_check: "/health"
      load_balancer: "round_robin"
      timeout: 30s
      retry_attempts: 3
      retry_delay: 1s

  # Path-based routing rules
  paths:
    # API v1 routing
    "/api/v1":
      upstream: "http://api-backend:3000"
      strip_prefix: true
      health_check: "/health"
      
    # API v2 routing
    "/api/v2":
      upstream: "http://api-backend:3000" 
      strip_prefix: true
      health_check: "/health"

# Middleware Configuration
middleware:
  # CORS Configuration
  cors:
    enabled: true
    allowed_origins:
      - "https://demo.keystone-gateway.dev"
      - "https://api.keystone-gateway.dev"
      - "*"  # Allow all for testing
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "PATCH"
      - "OPTIONS"
    allowed_headers:
      - "Origin"
      - "Content-Type"
      - "Accept"
      - "Authorization"
      - "X-Requested-With"
      - "X-API-Key"
    allow_credentials: true
    max_age: 86400

  # Rate Limiting (disabled for testing)
  rate_limit:
    enabled: false

  # Security Headers
  security:
    enabled: true
    headers:
      X-Frame-Options: "SAMEORIGIN"
      X-Content-Type-Options: "nosniff"
      X-XSS-Protection: "1; mode=block"

  # Request/Response Logging
  logging:
    enabled: true
    level: "info"
    format: "json"
    include_request_body: false
    include_response_body: false
    exclude_paths:
      - "/health"
      - "/admin/health"

  # Metrics and Monitoring
  metrics:
    enabled: true
    path: "/metrics"
    namespace: "keystone_gateway"

# Health Check Configuration
health:
  enabled: true
  path: "/health"
  timeout: 10s
  interval: 30s
  
# Circuit Breaker Configuration
circuit_breaker:
  enabled: true
  failure_threshold: 5
  recovery_timeout: 30s
  max_requests: 10

# Load Balancer Configuration
load_balancer:
  strategy: "round_robin"
  health_check_interval: 30s
  health_check_timeout: 10s
  max_idle_connections: 100
  max_connections_per_host: 50

# TLS Configuration (handled by Traefik)
tls:
  enabled: false
  auto_redirect: false

# Cache Configuration (disabled for simplicity)
cache:
  enabled: false

# Session Configuration (disabled for simplicity)
session:
  enabled: false

# Database Configuration (disabled for simplicity)
database:
  enabled: false

# Logging Configuration
log:
  level: "info"
  format: "json"
  output: "stdout"
  file:
    enabled: false

# Production Optimizations
production:
  max_workers: 0
  read_buffer_size: 4096
  write_buffer_size: 4096
  hide_server_header: true
  disable_server_header: true
  profiling_enabled: false
  debug_mode: false