version: '3.8'

services:
  keystone-gateway:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./configs:/app/configs
    command: ["./keystone-gateway", "-config", "/app/configs/config-with-lua.yaml", "-addr", ":8080"]
    depends_on:
      - lua-engine
    networks:
      - keystone-net

  lua-engine:
    build: ./lua-engine
    ports:
      - "8081:8081"
    volumes:
      - ./scripts:/app/scripts
    command: ["-addr", ":8081", "-scripts", "/app/scripts"]
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    networks:
      - keystone-net
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  # Example backend services for testing
  backend-stable:
    image: httpd:alpine
    ports:
      - "3000:80"
    volumes:
      - ./mock-backends/demo:/usr/local/apache2/htdocs
    networks:
      - keystone-net

  backend-canary:
    image: httpd:alpine
    ports:
      - "3001:80"
    volumes:
      - ./mock-backends/demo:/usr/local/apache2/htdocs
    networks:
      - keystone-net

networks:
  keystone-net:
    driver: bridge
