# Test Configuration for Tenant Route Namespacing Fix
# This config tests the collision fix by using multiple tenants

admin_base_path: "/admin"

lua_routing:
  enabled: true
  scripts_dir: "./scripts"

tenants:
  # Path-based tenant - routes mounted at /api
  - name: "api"
    path_prefix: "/api/"
    lua_routes: "basic-routes"
    health_interval: 30
    services:
      - name: "api-backend"
        url: "http://127.0.0.1:3001"
        health: "/health"

  # Different path-based tenant - routes mounted at /v2
  - name: "v2"
    path_prefix: "/v2/"
    lua_routes: "development-routes"
    health_interval: 30
    services:
      - name: "v2-backend"
        url: "http://127.0.0.1:3002"
        health: "/health"

  # Host-based tenant - routes mounted for specific domain
  - name: "app1"
    domains: ["app1.localhost", "app1.127.0.0.1.nip.io"]
    lua_routes: "my-first-routes"
    health_interval: 30
    services:
      - name: "app1-backend"
        url: "http://127.0.0.1:3003"
        health: "/health"