admin_base_path: "/admin"
server:
  port: "8080"
compression:
  enabled: true
  level: 5
lua_routing:
  enabled: true
  scripts_dir: "./scripts/lua"
tenants:
  - name: "keystone"
    path_prefix: "/"
    lua_routes: "oauth_middleware"
    health_interval: 30
    services:
      - name: "backend"
        url: "http://portal-test.lca-data.net/"
        health: "/"
